model:
  model_id: gpt_oss
  model_name_or_path: /home/data/gpt-oss-20b-hf/
  trust_remote_code: False
  train_from_scratch: False
  tokenizer_name_or_path: None

data:
  dataset: 
    file_name: "your origin data path.example: /home/train-00000-of-a09b74b3ef9c3b56.parquet"
  template: gpt
  cutoff_len: 4096
  max_samples: 100000
  overwrite_cache: True
  preprocessing_num_workers: 1
  data_manager_type: mg

parallel:
  fsdp_size: 16
  fsdp_modules:
    - model.layers.{*}
    - model.embed_tokens
    - lm_head
  tp_size: 1
  ep_size: 4
  ep_modules:
    - model.layers.{*}.mlp.experts
  ep_fsdp_size: 4
  ep_fsdp_modules:
    - model.layers.{*}.mlp.experts
  ep_dispatcher: eager
  recompute: True
  recompute_modules:
    - model.layers.{*}
  cp_size: 1
  cp_type: ulysses

training:
  stage: pt
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 1
  dataloader_num_workers : 1
  disable_shuffling: 1
  seed: 42
  dataloader_drop_last: True
  output_dir: ./output
  optimizer: adamw
  lr: 1.25e-06
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.99
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  lr_scheduler_type: cosine
  warmup_ratio: 0.0
  min_lr: 1.25e-7
  max_steps: 2000
  save_steps: 500
  logging_steps: 1

optimization:
  use_fused_rmsnorm: True
  moe_grouped_gemm: True
  use_fused_rotary_pos_emb: True